### ISSUE TITLE
is that can work????

### ISSUE THREAD

**Issue by hellojukay** [onrik/logrus#2]
package main
import (
	"github.com/onrik/logrus/filename"
	"github.com/onrik/logrus/sentry"
	log "github.com/sirupsen/logrus"
)

var (
	dsn = "http://60a0257d7b5a429a8838e5f2ba873ec9:cb785a64cd3649ea987a1f2f5fad5e82@example.com/1"
)

func main() {
	filenameHook := filename.NewHook()
	filenameHook.Field = "filename" // Customize source field name
	log.AddHook(filenameHook)

	sentryHook := sentry.NewHook(dsn, log.PanicLevel, log.FatalLevel, log.ErrorLevel)
	log.AddHook(sentryHook)

	log.WithFields(log.Fields{
	"a":"a",
	}).Info("Request info")
}

that is the log ouput:

time="2017-11-03T00:01:49+08:00" level=info msg="Request info" a=a filename="runtime/proc.go:185"

as you  can see ,th filename is error!

**Comment by onrik** [comment]
Hmm, it's interesting. I'll check it.

**Comment by onrik** [comment]
Looks like that [default skip param](https://github.com/onrik/logrus/blob/master/filename/filename.go#L13) is too high for your case. Try to decrease it.

**Comment by renathoaz** [comment]
@onrik why doesn't logrus have a default way to log filename and line? I could only achieve it with your hook.

**Comment by onrik** [comment]
@RenathoAzevedo, this [issue](https://github.com/sirupsen/logrus/issues/63) still open 😬

**Comment by RenathoAzevedo** [comment]
@onrik  sorry asking something to you that not related, but you have more experience on this, why logrus doesn't format the whole file to a valid json, only the lines are a valid json not the whole file. I have to edit the whole file to use a json viewer.
