### ISSUE TITLE
Would be nice if we have option to get function name

### ISSUE THREAD

**Issue by renathoaz** [onrik/logrus#3]
Would be nice if the hook has the option do display function name, just something like that could help:

```
        pc := make([]uintptr, 15)
	n := runtime.Callers(8, pc)
	frames := runtime.CallersFrames(pc[:n])
	frame, _ := frames.Next()
	return fmt.Sprintf("%s:%d - %s", frame.File, frame.Line, frame.Function)
```

**Comment by onrik** [comment]
I implemented function name logging. You can customize output:
```go
hook := filename.NewHook()
hook.Formatter = func(file, function string, line int) string {
  fmt.Sprintf("%s:%d - %s", file, line, function)
}
```

**Comment by renathoaz** [comment]
Excellent! Thank you!

**Comment by tzvatot** [comment]
> ```go
> func(file, function string, line int) string {
>   fmt.Sprintf("%s:%d - %s", file, line, function)
> }
> ```

missing "return" for fmt.Sprintf...
