### ISSUE TITLE
filename hook is not thread safe

### ISSUE THREAD

**Issue by davidklassen** [onrik/logrus#9]
This is an example that reproduces the problem. 
```go
package main

import (
	"github.com/onrik/logrus/filename"
	"github.com/sirupsen/logrus"
)

func main() {
	logger := logrus.New()
	logger.AddHook(filename.NewHook())
	l := logger.WithFields(logrus.Fields{"foo": "bar"})
	go func() {
		for {
			l.WithFields(nil)
		}
	}()
	go func() {
		for {
			l.Println("test")
		}
	}()
	for {
	}
}
```
Run it with `go run -race main.go > /dev/null`. 
Looks like the problem is in the `hook.Fire` function that modifies `entry.Data`.

**Comment by onrik** [comment]
Thanks. But i think it's read corner case when different goroutines modifying logrus.Entry data. Do you have any ideas how to fix it?

**Comment by davidklassen** [comment]
Maybe implementing a custom formatter that clones entry.Data instead of modifying entry.Data directly can help. I'll try this approach and if it works I'll make a PR.
